#!/bin/bash
set -euo pipefail

echo "=== Building Debian Package ==="

# Run build in Docker container
docker run --rm \
    -v "$(pwd):/build" \
    -w /build \
    rust-debtools:latest \
    bash -c '
        set -euo pipefail

        echo "Building for aarch64 (arm64)..."

        # Build the release binary
        cargo build --release --target aarch64-unknown-linux-gnu

        # Get version from Cargo.toml
        VERSION=$(grep "^version" Cargo.toml | head -1 | sed "s/.*\"\(.*\)\"/\1/")
        PACKAGE_NAME="homarr-container-adapter"

        echo "Package: ${PACKAGE_NAME}"
        echo "Version: ${VERSION}"

        # Create package directory structure
        PKG_DIR="${PACKAGE_NAME}_${VERSION}_arm64"
        rm -rf "$PKG_DIR"
        mkdir -p "$PKG_DIR/DEBIAN"
        mkdir -p "$PKG_DIR/usr/bin"
        mkdir -p "$PKG_DIR/lib/systemd/system"
        mkdir -p "$PKG_DIR/etc/homarr-container-adapter"
        mkdir -p "$PKG_DIR/var/lib/homarr-container-adapter"

        # Copy binary
        cp target/aarch64-unknown-linux-gnu/release/homarr-container-adapter "$PKG_DIR/usr/bin/"
        chmod 755 "$PKG_DIR/usr/bin/homarr-container-adapter"

        # Copy systemd service
        cp debian/homarr-container-adapter.service "$PKG_DIR/lib/systemd/system/"

        # Read debian version from changelog (generated by CI)
        if [ -f debian/changelog ]; then
            DEB_VERSION=$(head -1 debian/changelog | sed "s/.*(\(.*\)).*/\1/")
        else
            DEB_VERSION="${VERSION}-1"
        fi

        # Create control file
        cat > "$PKG_DIR/DEBIAN/control" << EOF
Package: ${PACKAGE_NAME}
Version: ${DEB_VERSION}
Architecture: arm64
Maintainer: Hat Labs Ltd <info@hatlabs.fi>
Depends: homarr-branding-halos
Description: Homarr dashboard adapter for HaLOS
 Adapter service that handles first-boot setup and container
 auto-discovery for the Homarr dashboard.
 .
 Features:
  - Completes Homarr onboarding with HaLOS branding
  - Creates admin user and default dashboard
  - Watches Docker events for real-time container discovery
  - Auto-adds containers with homarr.* labels to dashboard
EOF

        # Create postinst script
        cat > "$PKG_DIR/DEBIAN/postinst" << "POSTINST"
#!/bin/sh
set -e

case "$1" in
    configure)
        # Create state directory with proper permissions
        mkdir -p /var/lib/homarr-container-adapter
        chmod 700 /var/lib/homarr-container-adapter

        # Enable and start the service
        if [ -d /run/systemd/system ]; then
            systemctl daemon-reload
            systemctl enable homarr-container-adapter.service
        fi
        ;;
esac

#DEBHELPER#

exit 0
POSTINST
        chmod 755 "$PKG_DIR/DEBIAN/postinst"

        # Create postrm script
        cat > "$PKG_DIR/DEBIAN/postrm" << "POSTRM"
#!/bin/sh
set -e

case "$1" in
    purge)
        rm -rf /var/lib/homarr-container-adapter
        rm -rf /etc/homarr-container-adapter
        ;;
esac

#DEBHELPER#

exit 0
POSTRM
        chmod 755 "$PKG_DIR/DEBIAN/postrm"

        # Build the package
        dpkg-deb --build "$PKG_DIR"

        # Rename to standard format
        mv "${PKG_DIR}.deb" "${PACKAGE_NAME}_${DEB_VERSION}_arm64.deb"

        echo "=== Package built successfully ==="
        ls -la *.deb
    '

# Package is already in workspace root (Docker volume mount)
# Just verify it exists
echo "=== Build complete ==="
ls -la *.deb
